version: '3.8'
services:
  mariadb:
    image: mariadb:10.5.8
    restart: on-failure
    volumes:
    - ./dashboard/sql/dashboard.sql:/docker-entrypoint-initdb.d/dashboard.sql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
    - "3306:3306"

  adminer:
    image: adminer
    restart: on-failure
    ports:
    - '80:8080'

  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
    - './dashboard/public/:/usr/src/app'
    - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
    - '8080:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - ./dashboard/.env
    user: 1000:1000